# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'ZayFi-iOS.xcodeproj'
target 'ZayFi-iOS' do
  use_frameworks!

	pod 'MBProgressHUD'
	pod 'IQKeyboardManagerSwift'
  pod 'SkyFloatingLabelTextField'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'SKCountryPicker'

end
